name: Publish to npm registy
on:
    release:
        types: [published]
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [15.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: install
            - name: Build package
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: build
            - name: Publish to NPM registry
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
