name: Publish to npm registry
on:
    release:
        types: [published]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: pnpm install
            - name: Build package
              run: pnpm build
            - name: Run tests
              run: pnpm test
            - name: Publish to npm registry
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm publish
