name: Publish to npm registry
on:
    release:
        types: [published]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
              with:
                  persist-credentials: false
                  fetch-depth: 0
                  ref: 'main'
            - name: Enable corepack
              run: corepack enable
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"
            - name: Install dependencies
              run: corepack pnpm install --frozen-lockfile
            - name: Run tests
              run: corepack pnpm test
            - name: Build package
              run: corepack pnpm build
            - name: Publish to npm registry
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: corepack pnpm publish
