name: Publish to npm registry
on:
    release:
        types: [published]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: install
            - name: Build package
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: build
            - name: Run tests
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: test
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
