name: Publish to npm registry
on:
    release:
        types: [published]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - name: Install dependencies
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: install
            - name: Run tests
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: test
            - name: Build package
              uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: build
            - name: Publish to NPM registry
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
