name: Publish to npm registry
on:
    release:
        types: [published]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.1
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build package
              run: pnpm build
            - name: Run tests
              run: pnpm test
            - name: Publish to npm registry
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm publish
